on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: generate build system
        run: cmake -S . -B build -DSBASH64_TESTCPPLITE_ENABLE_TESTS=1 -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cmake --build build --config Release
      - name: test
        run: |
          cd build 
          ctest -C Release -V
