name: ctest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test ${{ matrix.compiler }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [g++, clang++]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: generate build system
      env:
        CXX: ${{ matrix.compiler }}
      run: cmake -S . -B build -DWITH_TESTS=1 -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
